#!/bin/zsh
set -euo pipefail

ROOT_DIR="$(cd -- "$(dirname "$0")/.." && pwd)"
VAULT_PATH="${1:-${OBSIDIAN_VAULT_PATH:-}}"
CONFIG_PATH="${DEEP_OBSIDIAN_CONFIG_PATH:-}"
SERVER_BIN="${DEEP_OBSIDIAN_SERVER_BIN:-${ROOT_DIR}/bin/deep-obsidian-mcp}"

HOST="${DEEP_OBSIDIAN_HOST:-127.0.0.1}"
PORT="${DEEP_OBSIDIAN_PORT:-4100}"
MCP_PATH="${DEEP_OBSIDIAN_MCP_PATH:-/mcp}"
HEALTH_PATH="${DEEP_OBSIDIAN_HEALTH_PATH:-/healthz}"
EMBEDDING_PROVIDER_VALUE="${DEEP_OBSIDIAN_EMBEDDING_PROVIDER:-${EMBEDDING_PROVIDER:-}}"
EMBEDDING_MODEL_VALUE="${DEEP_OBSIDIAN_EMBEDDING_MODEL:-${EMBEDDING_MODEL:-${OPENAI_EMBEDDING_MODEL:-}}}"
EMBEDDING_BASE_URL_VALUE="${DEEP_OBSIDIAN_EMBEDDING_BASE_URL:-${EMBEDDING_BASE_URL:-${OPENAI_BASE_URL:-}}}"
EMBEDDING_API_KEY_VALUE="${DEEP_OBSIDIAN_EMBEDDING_API_KEY:-${EMBEDDING_API_KEY:-${OPENAI_API_KEY:-}}}"

if [[ -z "${EMBEDDING_PROVIDER_VALUE}" && -n "${EMBEDDING_MODEL_VALUE}" ]]; then
  EMBEDDING_PROVIDER_VALUE="openai-compatible"
fi

if [[ -n "${EMBEDDING_PROVIDER_VALUE}" ]]; then
  export EMBEDDING_PROVIDER="${EMBEDDING_PROVIDER_VALUE}"
fi
if [[ -n "${EMBEDDING_MODEL_VALUE}" ]]; then
  export EMBEDDING_MODEL="${EMBEDDING_MODEL_VALUE}"
fi
if [[ -n "${EMBEDDING_BASE_URL_VALUE}" ]]; then
  export EMBEDDING_BASE_URL="${EMBEDDING_BASE_URL_VALUE}"
fi
if [[ -n "${EMBEDDING_API_KEY_VALUE}" ]]; then
  export EMBEDDING_API_KEY="${EMBEDDING_API_KEY_VALUE}"
fi
export DEEP_OBSIDIAN_PACKAGED="${DEEP_OBSIDIAN_PACKAGED:-1}"

typeset -a args
args=(
  "serve"
  "--packaged"
  "--transport" "http"
  "--host" "${HOST}"
  "--port" "${PORT}"
  "--mcp-path" "${MCP_PATH}"
  "--health-path" "${HEALTH_PATH}"
)

if [[ -n "${CONFIG_PATH}" ]]; then
  args+=("--config" "${CONFIG_PATH}")
fi
if [[ -n "${VAULT_PATH}" ]]; then
  args+=("--vault" "${VAULT_PATH}")
fi

exec "${SERVER_BIN}" "${args[@]}"
