// Bundles the sidecar into a single ESM file that Node can run with no
// node_modules present, so the Rust supervisor only ships `dist/sidecar.mjs`.
//
// Two non-obvious build requirements:
//
//   * `banner` injects a CommonJS `require`. The whole pouchdb-* dependency
//     tree that commonlib pulls in is CJS and calls `require("events")` at
//     module scope; esbuild's ESM output otherwise emits a `__require` stub
//     that throws "Dynamic require of \"events\" is not supported" the moment
//     pouchdb-core is evaluated.
//   * `platform: "node"` selects commonlib's `#worker` import-map `node`
//     branch (`bgWorker.direct`). The browser branch would drag in `Worker`.
//
// xxhash-wasm arrives via octagonal-wheels' patched copy, which embeds the
// module as a `Uint8Array` literal, so no `.wasm` side-asset is produced and
// the bundle stays self-contained.
import { build } from "esbuild";
import { fileURLToPath } from "node:url";
import * as path from "node:path";
import * as fs from "node:fs";

const here = path.dirname(fileURLToPath(import.meta.url));
const root = path.resolve(here, "..");

const result = await build({
    entryPoints: [path.join(root, "src", "main.ts")],
    outfile: path.join(root, "dist", "sidecar.mjs"),
    bundle: true,
    platform: "node",
    format: "esm",
    target: "node20",
    // No `external`: the supervisor runs the bundle standalone.
    external: [],
    banner: {
        js: [
            "// @generated by scripts/build.mjs -- do not edit.",
            'import { createRequire as __sidecarCreateRequire } from "node:module";',
            "const require = __sidecarCreateRequire(import.meta.url);",
        ].join("\n"),
    },
    logLevel: "info",
    metafile: true,
    sourcemap: false,
    minify: false,
});

const bytes = fs.statSync(path.join(root, "dist", "sidecar.mjs")).size;
process.stderr.write(`sidecar bundle: ${(bytes / 1024).toFixed(0)} KiB\n`);
fs.writeFileSync(path.join(root, "dist", "meta.json"), JSON.stringify(result.metafile));
